using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class Exercise1 : MonoBehaviour
{
    public TextMeshProUGUI NumberText;

    void Start()
    {
        /*I have also put this line here because I wanted to display 
        a random number before pressing the button at the start of the game*/
        NumberText.text = Random.Range(0, 100).ToString();
    }

    public void RandomNumber()
    {
        //A text in a canvas will show the random number generated by the button
        NumberText.text = Random.Range(0, 100).ToString();
    }
}
